[application]

[web.app]

# HTML title tag content
title = "alignment_rs"

# Additional CSS style files
style = []

[bundle]
identifier = "AlignmentRs.app"
description = "Desktop app for visualizing the Smith-Waterman algorithm"
publisher = "Oscar Aspelin"
